package com.tomlin7.l0v3.keyboard

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.inputmethodservice.InputMethodService
import android.media.projection.MediaProjectionManager
import android.os.Build
import android.util.Log
import android.view.View
import android.view.inputmethod.EditorInfo
import android.widget.Toast
import androidx.compose.animation.core.*
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsPressedAsState
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.Backspace
import androidx.compose.material.icons.filled.Favorite
import androidx.compose.ui.res.painterResource
import com.tomlin7.l0v3.R
import androidx.compose.material.icons.filled.Keyboard
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.platform.ComposeView
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.compose.ui.draw.scale
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleOwner
import androidx.lifecycle.setViewTreeLifecycleOwner
import androidx.compose.ui.platform.ViewCompositionStrategy
import androidx.savedstate.setViewTreeSavedStateRegistryOwner
import com.tomlin7.l0v3.MainActivity
import com.tomlin7.l0v3.api.GeminiService
import com.tomlin7.l0v3.data.PreferencesRepository
import com.tomlin7.l0v3.data.UserPreferences
import com.tomlin7.l0v3.data.ThemeMode
import com.tomlin7.l0v3.service.ScreenshotDetectionService
import com.tomlin7.l0v3.ui.theme.L0V3Theme
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch

class L0V3KeyboardService : InputMethodService(), LifecycleOwner {
    
    private lateinit var preferencesRepository: PreferencesRepository
    private var geminiService: GeminiService? = null
    private val serviceScope = CoroutineScope(Dispatchers.Main + SupervisorJob())
    
    private var keyboardState by mutableStateOf(KeyboardState.IDLE)
    private var replySuggestions by mutableStateOf<List<String>>(emptyList())
    private var errorMessage by mutableStateOf<String?>(null)
    
    private var latestScreenshot: Bitmap? = null
    private var screenshotTimestamp: Long = 0
    private var autoGeneratedReplies: List<String> = emptyList()
    
    override val lifecycle: Lifecycle
        get() = lifecycleOwner.lifecycle
    
    private val lifecycleOwner = KeyboardLifecycleOwner()
    
    enum class KeyboardState {
        IDLE,
        CAPTURING,
        GENERATING,
        COOKING,
        SHOWING_SUGGESTIONS,
        ERROR
    }
    
    override fun onCreate() {
        super.onCreate()
        preferencesRepository = PreferencesRepository(this)
        
        serviceScope.launch {
            val prefs = preferencesRepository.userPreferencesFlow.first()
            if (prefs.geminiApiKey.isNotEmpty()) {
                geminiService = GeminiService(prefs.geminiApiKey)
            }
        }
        
        // Start screenshot detection service
        startScreenshotDetectionService()
        
        // Set up callback for when screenshots are detected
        ScreenshotDetectionService.onScreenshotDetected = { bitmap ->
            latestScreenshot = bitmap
            screenshotTimestamp = System.currentTimeMillis()
            keyboardState = KeyboardState.COOKING
            Log.d("L0V3Keyboard", "Screenshot detected! Cooking replies...")
        }
        
        // Set up auto-reply generation callback
        ScreenshotDetectionService.onAutoReplyGenerated = { replies ->
            autoGeneratedReplies = replies
            replySuggestions = replies
            keyboardState = KeyboardState.SHOWING_SUGGESTIONS
            Log.d("L0V3Keyboard", "Auto-generated ${replies.size} replies")
        }
        
        lifecycleOwner.onCreate()
    }
    
    override fun onCreateInputView(): View {
        lifecycleOwner.onResume()
        
        // Set lifecycle owner on the InputMethodService window's DecorView
        window?.window?.decorView?.let { decorView ->
            decorView.setViewTreeLifecycleOwner(lifecycleOwner)
            decorView.setViewTreeSavedStateRegistryOwner(lifecycleOwner)
        }
        
        return ComposeView(this).apply {
            // Use DisposeOnDetachedFromWindowOrReleasedFromPool strategy for IME
            setViewCompositionStrategy(
                ViewCompositionStrategy.DisposeOnDetachedFromWindowOrReleasedFromPool
            )
            
            setContent {
                val userPreferences by preferencesRepository.userPreferencesFlow.collectAsState(
                    initial = UserPreferences()
                )
                
                val systemInDarkTheme = isSystemInDarkTheme()
                val isDarkTheme = when (userPreferences.themeMode) {
                    ThemeMode.LIGHT -> false
                    ThemeMode.DARK -> true
                    ThemeMode.SYSTEM -> systemInDarkTheme
                }
                
                L0V3Theme(themeMode = userPreferences.themeMode) {
                    KeyboardContent(
                        state = keyboardState,
                        suggestions = replySuggestions,
                        errorMessage = errorMessage,
                        isDarkTheme = isDarkTheme,
                        onHeartClick = ::onHeartButtonClicked,
                        onSuggestionClick = ::onSuggestionClicked,
                        onSettingsClick = ::openSettings,
                        onSwitchKeyboard = ::switchToNextKeyboard,
                        onBackspaceClick = ::onBackspaceClicked
                    )
                }
            }
        }
    }
    
    override fun onStartInputView(info: EditorInfo?, restarting: Boolean) {
        super.onStartInputView(info, restarting)
        keyboardState = KeyboardState.IDLE
        replySuggestions = emptyList()
        errorMessage = null
    }
    
    override fun onFinishInputView(finishingInput: Boolean) {
        super.onFinishInputView(finishingInput)
        // Don't pause here as the view might be reused
    }
    
    override fun onDestroy() {
        super.onDestroy()
        lifecycleOwner.onDestroy()
        stopScreenshotService()
    }
    
    private fun onHeartButtonClicked() {
        serviceScope.launch {
            val prefs = preferencesRepository.userPreferencesFlow.first()
            
            if (prefs.geminiApiKey.isEmpty()) {
                keyboardState = KeyboardState.ERROR
                errorMessage = "Please set your Gemini API key in settings"
                return@launch
            }
            
            if (geminiService == null) {
                geminiService = GeminiService(prefs.geminiApiKey)
            }
            
            // Check if we have auto-generated replies first
            if (autoGeneratedReplies.isNotEmpty()) {
                replySuggestions = autoGeneratedReplies
                keyboardState = KeyboardState.SHOWING_SUGGESTIONS
                return@launch
            }
            
            // Check if we have a recent screenshot
            val screenshot = latestScreenshot
            val timeSinceScreenshot = System.currentTimeMillis() - screenshotTimestamp
            
            if (screenshot != null && timeSinceScreenshot < 10000) {
                // Screenshot is recent (less than 10 seconds old), use it!
                generateReplies(screenshot, prefs)
            } else {
                // No recent screenshot, ask user to take one
                keyboardState = KeyboardState.ERROR
                errorMessage = "Please take a screenshot first (Power + Volume Down), then tap ❤️"
            }
        }
    }
    
    private fun startScreenshotDetectionService() {
        val intent = Intent(this, ScreenshotDetectionService::class.java).apply {
            action = ScreenshotDetectionService.ACTION_START
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            startForegroundService(intent)
        } else {
            startService(intent)
        }
    }
    
    private fun generateReplies(screenshot: Bitmap, prefs: UserPreferences) {
        serviceScope.launch {
            keyboardState = KeyboardState.GENERATING
            
            val result = geminiService?.generateReplies(screenshot, prefs)
            
            result?.onSuccess { suggestions ->
                replySuggestions = suggestions
                keyboardState = KeyboardState.SHOWING_SUGGESTIONS
                Log.d("L0V3Keyboard", "Generated ${suggestions.size} suggestions")
            }?.onFailure { error ->
                keyboardState = KeyboardState.ERROR
                errorMessage = "Failed to generate replies: ${error.message}"
                Log.e("L0V3Keyboard", "Error generating replies", error)
            }
        }
    }
    
    private fun onSuggestionClicked(suggestion: String) {
        val ic = currentInputConnection
        if (ic != null) {
            ic.commitText(suggestion, 1)
            // Reset state
            keyboardState = KeyboardState.IDLE
            replySuggestions = emptyList()
        }
    }
    
    private fun openSettings() {
        val intent = Intent(this, MainActivity::class.java).apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        startActivity(intent)
    }
    
    private fun switchToNextKeyboard() {
        try {
            val imeManager = getSystemService(Context.INPUT_METHOD_SERVICE) as android.view.inputmethod.InputMethodManager
            imeManager.showInputMethodPicker()
        } catch (e: Exception) {
            Log.e("L0V3Keyboard", "Error switching keyboard", e)
        }
    }
    
    private fun onBackspaceClicked() {
        currentInputConnection?.deleteSurroundingText(1, 0)
    }
    
    private fun stopScreenshotService() {
        val intent = Intent(this, ScreenshotDetectionService::class.java).apply {
            action = ScreenshotDetectionService.ACTION_STOP
        }
        startService(intent)
        ScreenshotDetectionService.onScreenshotDetected = null
    }
}

@Composable
fun KeyboardContent(
    state: L0V3KeyboardService.KeyboardState,
    suggestions: List<String>,
    errorMessage: String?,
    isDarkTheme: Boolean,
    onHeartClick: () -> Unit,
    onSuggestionClick: (String) -> Unit,
    onSettingsClick: () -> Unit,
    onSwitchKeyboard: () -> Unit,
    onBackspaceClick: () -> Unit
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .background(MaterialTheme.colorScheme.background)
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        when (state) {
            L0V3KeyboardService.KeyboardState.IDLE -> {
                IdleState(
                    isDarkTheme = isDarkTheme,
                    onHeartClick = onHeartClick,
                    onSettingsClick = onSettingsClick,
                    onSwitchKeyboard = onSwitchKeyboard,
                    onBackspaceClick = onBackspaceClick
                )
            }
            L0V3KeyboardService.KeyboardState.CAPTURING -> {
                LoadingState("Capturing screenshot...")
            }
            L0V3KeyboardService.KeyboardState.GENERATING -> {
                LoadingState("Generating replies...")
            }
            L0V3KeyboardService.KeyboardState.COOKING -> {
                CookingState(isDarkTheme = isDarkTheme)
            }
            L0V3KeyboardService.KeyboardState.SHOWING_SUGGESTIONS -> {
                SuggestionsState(
                    suggestions = suggestions,
                    onSuggestionClick = onSuggestionClick,
                    onBackClick = onHeartClick,
                    onSwitchKeyboard = onSwitchKeyboard,
                    onBackspaceClick = onBackspaceClick
                )
            }
            L0V3KeyboardService.KeyboardState.ERROR -> {
                ErrorState(
                    message = errorMessage ?: "Something went wrong",
                    onRetryClick = onHeartClick
                )
            }
        }
    }
}

@Composable
fun IdleState(
    isDarkTheme: Boolean,
    onHeartClick: () -> Unit,
    onSettingsClick: () -> Unit,
    onSwitchKeyboard: () -> Unit,
    onBackspaceClick: () -> Unit
) {
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier.fillMaxWidth()
    ) {
        Spacer(modifier = Modifier.height(16.dp))
        
        Text(
            text = "Take a screenshot",
            style = MaterialTheme.typography.bodyLarge,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            textAlign = TextAlign.Center
        )

        Spacer(modifier = Modifier.height(8.dp))

        Text(
            text = "We'll do the rest",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            textAlign = TextAlign.Center
        )

        Spacer(modifier = Modifier.height(16.dp))

        Image(
            painter = painterResource(
                id = if (isDarkTheme) R.drawable.heart_transparent
                     else R.drawable.heart_transparent_light
            ),
            contentDescription = "Generate replies",
            modifier = Modifier.size(100.dp)
        )

        Spacer(modifier = Modifier.height(8.dp))

        val softGreyColor = if (isDarkTheme) Color(0xFF2A2A2A) else Color(0xFFF5F5F5)
        val iconColor = if (isDarkTheme) Color(0xFFE0E0E0) else Color(0xFF424242)
        

        // Bottom controls
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            // Backspace button (right)
            IconButton(
                onClick = onSettingsClick,
                modifier = Modifier
                    .size(48.dp)
                    .background(
                        color = softGreyColor,
                        shape = RoundedCornerShape(12.dp)
                    )
            ) {
                Icon(
                    imageVector = Icons.Default.Settings,
                    contentDescription = "Settings",
                    tint = iconColor,
                    modifier = Modifier.size(24.dp)
                )
            }

            // Backspace button (right)
            IconButton(
                onClick = onBackspaceClick,
                modifier = Modifier
                    .size(48.dp)
                    .background(
                        color = softGreyColor,
                        shape = RoundedCornerShape(12.dp)
                    )
            ) {
                Icon(
                    imageVector = Icons.AutoMirrored.Filled.Backspace,
                    contentDescription = "Backspace",
                    tint = iconColor,
                    modifier = Modifier.size(24.dp)
                )
            }
        }
    }
}

@Composable
fun LoadingState(message: String) {
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier.padding(32.dp)
    ) {
        CircularProgressIndicator(
            color = MaterialTheme.colorScheme.primary,
            modifier = Modifier.size(48.dp)
        )
        Spacer(modifier = Modifier.height(16.dp))
        Text(
            text = message,
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )
    }
}

@Composable
fun CookingState(isDarkTheme: Boolean) {
    val infiniteTransition = rememberInfiniteTransition(label = "cooking")
    val scale by infiniteTransition.animateFloat(
        initialValue = 1f,
        targetValue = 1.2f,
        animationSpec = infiniteRepeatable(
            animation = tween(800, easing = EaseInOut),
            repeatMode = RepeatMode.Reverse
        ),
        label = "heart_scale"
    )
    
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier.padding(32.dp)
    ) {
        Image(
            painter = painterResource(
                id = if (isDarkTheme) R.drawable.heart_transparent
                else R.drawable.heart_transparent_light
            ),
            contentDescription = "Generate replies",
            modifier = Modifier
                .size(64.dp)
                .scale(scale)
        )
        
        Spacer(modifier = Modifier.height(16.dp))
        
        Text(
            text = "Cooking...",
            style = MaterialTheme.typography.headlineSmall,
            color = MaterialTheme.colorScheme.primary,
            fontWeight = FontWeight.Bold,
            textAlign = TextAlign.Center
        )
        
        Spacer(modifier = Modifier.height(8.dp))
        
        Text(
            text = "generating some rizz for you",
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            textAlign = TextAlign.Center
        )
    }
}

@Composable
fun SuggestionsState(
    suggestions: List<String>,
    onSuggestionClick: (String) -> Unit,
    onBackClick: () -> Unit,
    onSwitchKeyboard: () -> Unit,
    onBackspaceClick: () -> Unit
) {
    Column(modifier = Modifier.fillMaxWidth()) {
        Spacer(modifier = Modifier.height(12.dp))

        suggestions.forEachIndexed { index, suggestion ->
            SuggestionCard(
                text = suggestion,
                onClick = { onSuggestionClick(suggestion) }
            )
            if (index < suggestions.size - 1) {
                Spacer(modifier = Modifier.height(8.dp))
            }
        }
        
        Spacer(modifier = Modifier.height(16.dp))
        
        // Bottom row with keyboard, generate, and backspace buttons
        val isDarkTheme = MaterialTheme.colorScheme.background == Color(0xFF121212)
        val softGreyColor = if (isDarkTheme) Color(0xFF2A2A2A) else Color(0xFFF5F5F5)
        val iconColor = if (isDarkTheme) Color(0xFFE0E0E0) else Color(0xFF424242)
        
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            // Keyboard switch button (left)
            IconButton(
                onClick = onSwitchKeyboard,
                modifier = Modifier
                    .size(48.dp)
                    .background(
                        color = softGreyColor,
                        shape = RoundedCornerShape(12.dp)
                    )
            ) {
                Icon(
                    imageVector = Icons.Default.Keyboard,
                    contentDescription = "Switch keyboard",
                    tint = iconColor,
                    modifier = Modifier.size(24.dp)
                )
            }
            
            // Generate more rizz button (center)
            Button(
                onClick = onBackClick,
                colors = ButtonDefaults.buttonColors(
                    containerColor = softGreyColor
                ),
                shape = RoundedCornerShape(12.dp)
            ) {
                Text(
                    text = "Generate more rizz",
                    color = iconColor,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                    fontWeight = FontWeight.Medium
                )
            }
            
            // Backspace button (right)
            IconButton(
                onClick = onBackspaceClick,
                modifier = Modifier
                    .size(48.dp)
                    .background(
                        color = softGreyColor,
                        shape = RoundedCornerShape(12.dp)
                    )
            ) {
                Icon(
                    imageVector = Icons.AutoMirrored.Filled.Backspace,
                    contentDescription = "Backspace",
                    tint = iconColor,
                    modifier = Modifier.size(24.dp)
                )
            }
        }
    }
}

@Composable
fun SuggestionCard(text: String, onClick: () -> Unit) {
    val interactionSource = remember { MutableInteractionSource() }
    val isPressed by interactionSource.collectIsPressedAsState()
    
    // Animation for press effect
    val scale by animateFloatAsState(
        targetValue = if (isPressed) 0.95f else 1f,
        animationSpec = spring(
            dampingRatio = Spring.DampingRatioMediumBouncy,
            stiffness = Spring.StiffnessLow
        ),
        label = "scale"
    )
    
    val glowAlpha by animateFloatAsState(
        targetValue = if (isPressed) 0.4f else 0.2f,
        animationSpec = tween(150),
        label = "glow"
    )
    
    val isDarkTheme = MaterialTheme.colorScheme.background == Color(0xFF121212)
    val crimsonRed = Color(0xFFDC143C) // Crimson red color
    
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .graphicsLayer {
                scaleX = scale
                scaleY = scale
            }
            .shadow(
                elevation = if (isPressed) 12.dp else 6.dp,
                shape = RoundedCornerShape(20.dp),
                ambientColor = crimsonRed.copy(alpha = glowAlpha * 0.3f),
                spotColor = crimsonRed.copy(alpha = glowAlpha * 0.5f),
                clip = false
            )
            .background(
                brush = Brush.verticalGradient(
                    colors = if (isDarkTheme) {
                        listOf(
                            Color(0x50DC143C), // Crimson with transparency
                            Color(0x40DC143C),
                            Color(0x30DC143C)
                        )
                    } else {
                        listOf(
                            Color(0x70DC143C), // More opaque crimson for light theme
                            Color(0x60DC143C),
                            Color(0x50DC143C)
                        )
                    }
                ),
                shape = RoundedCornerShape(20.dp)
            )
            .background(
                brush = Brush.radialGradient(
                    colors = listOf(
                        crimsonRed.copy(alpha = 0.15f),
                        Color.Transparent
                    ),
                    radius = 300f
                ),
                shape = RoundedCornerShape(20.dp)
            )
            .clickable(
                interactionSource = interactionSource,
                indication = null,
                onClick = onClick
            )
    ) {
        Text(
            text = text,
            modifier = Modifier
                .fillMaxWidth()
                .padding(20.dp),
            style = MaterialTheme.typography.bodyMedium,
            color = Color.White, // White text for good contrast against crimson
            fontWeight = FontWeight.SemiBold,
            textAlign = TextAlign.Center
        )
    }
}

@Composable
fun ErrorState(message: String, onRetryClick: () -> Unit) {
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier.padding(24.dp)
    ) {
        Text(
            text = "Did you take screenshot?",
            fontSize = 48.sp
        )
        Spacer(modifier = Modifier.height(12.dp))
        Text(
            text = message,
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            textAlign = TextAlign.Center
        )
        Spacer(modifier = Modifier.height(16.dp))
        Button(
            onClick = onRetryClick,
            colors = ButtonDefaults.buttonColors(
                containerColor = MaterialTheme.colorScheme.primary
            )
        ) {
            Text("Retry")
        }
    }
}
