package com.tomlin7.cupidly.keyboard

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.inputmethodservice.InputMethodService
import android.os.Build
import android.util.Log
import android.view.View
import android.view.inputmethod.EditorInfo
import androidx.compose.foundation.Image
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.ComposeView
import androidx.compose.ui.platform.ViewCompositionStrategy
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleOwner
import androidx.lifecycle.setViewTreeLifecycleOwner
import androidx.savedstate.setViewTreeSavedStateRegistryOwner
import com.tomlin7.cupidly.MainActivity
import com.tomlin7.cupidly.api.ApiService
import com.tomlin7.cupidly.data.PreferencesRepository
import com.tomlin7.cupidly.data.ThemeMode
import com.tomlin7.cupidly.data.UserPreferences
import com.tomlin7.cupidly.service.ScreenshotDetectionService
import com.tomlin7.cupidly.ui.keyboard.KeyboardMessage
import com.tomlin7.cupidly.ui.keyboard.KeyboardPanel
import com.tomlin7.cupidly.ui.theme.CupidlyTheme
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch

class CupidlyKeyboardService : InputMethodService(), LifecycleOwner {

    private lateinit var preferencesRepository: PreferencesRepository
    private var apiService: ApiService? = null
    private val serviceScope = CoroutineScope(Dispatchers.Main + SupervisorJob())

    private var keyboardState by mutableStateOf(KeyboardState.IDLE)
    private var replySuggestions by mutableStateOf<List<String>>(emptyList())
    private var sentMessages by mutableStateOf<List<String>>(emptyList())
    private var errorMessage by mutableStateOf<String?>(null)
    private var latestScreenshot by mutableStateOf<Bitmap?>(null)

    private var screenshotTimestamp: Long = 0
    private var autoGeneratedReplies: List<String> = emptyList()

    override val lifecycle: Lifecycle
        get() = lifecycleOwner.lifecycle

    private val lifecycleOwner = KeyboardLifecycleOwner()

    enum class KeyboardState {
        IDLE,
        CAPTURING,
        GENERATING,
        COOKING,
        SHOWING_SUGGESTIONS,
        ERROR
    }

    override fun onCreate() {
        super.onCreate()
        preferencesRepository = PreferencesRepository(this)

        // Initialize API service
        apiService = ApiService()

        // Start screenshot detection service
        startScreenshotDetectionService()

        // Set up callback for when screenshots are detected
        ScreenshotDetectionService.onScreenshotDetected = { bitmap ->
            latestScreenshot = bitmap
            screenshotTimestamp = System.currentTimeMillis()
            keyboardState = KeyboardState.COOKING
            Log.d("CupidlyKeyboard", "Screenshot detected! Cooking replies...")
        }

        // Set up auto-reply generation callback
        ScreenshotDetectionService.onAutoReplyGenerated = { replies ->
            autoGeneratedReplies = replies
            replySuggestions = replies
            keyboardState = KeyboardState.SHOWING_SUGGESTIONS
            Log.d("CupidlyKeyboard", "Auto-generated ${replies.size} replies")
        }

        lifecycleOwner.onCreate()
    }

    override fun onCreateInputView(): View {
        lifecycleOwner.onResume()

        // Set lifecycle owner on the InputMethodService window's DecorView
        window?.window?.decorView?.let { decorView ->
            decorView.setViewTreeLifecycleOwner(lifecycleOwner)
            decorView.setViewTreeSavedStateRegistryOwner(lifecycleOwner)
        }

        return ComposeView(this).apply {
            // Use DisposeOnDetachedFromWindowOrReleasedFromPool strategy for IME
            setViewCompositionStrategy(
                ViewCompositionStrategy.DisposeOnDetachedFromWindowOrReleasedFromPool
            )

            setContent {
                val userPreferences by preferencesRepository.userPreferencesFlow.collectAsState(
                    initial = UserPreferences()
                )

                val systemInDarkTheme = isSystemInDarkTheme()
                val isDarkTheme = when (userPreferences.themeMode) {
                    ThemeMode.LIGHT -> false
                    ThemeMode.DARK -> true
                    ThemeMode.SYSTEM -> systemInDarkTheme
                }

                CupidlyTheme(themeMode = userPreferences.themeMode) {
                    val screenshot = latestScreenshot

                    KeyboardPanel(
                        state = keyboardState,
                        messages = buildTranscript(),
                        errorMessage = errorMessage,
                        isDarkTheme = isDarkTheme,
                        onGenerate = ::onGenerateClicked,
                        onSuggestionClick = ::onSuggestionClicked,
                        onSettingsClick = ::openSettings,
                        onSwitchKeyboard = ::switchToNextKeyboard,
                        onBackspaceClick = ::onBackspaceClicked,
                        thumbnail = if (screenshot != null) {
                            {
                                Image(
                                    bitmap = screenshot.asImageBitmap(),
                                    contentDescription = "Captured screenshot",
                                    contentScale = ContentScale.Crop,
                                    modifier = Modifier.fillMaxSize()
                                )
                            }
                        } else {
                            null
                        }
                    )
                }
            }
        }
    }

    /**
     * Sent replies stay in the transcript above the fresh suggestions, so the
     * conversation reads as a chat you can keep following up in.
     */
    private fun buildTranscript(): List<KeyboardMessage> =
        sentMessages.map { KeyboardMessage(text = it, outgoing = true, sent = true) } +
            replySuggestions.map { KeyboardMessage(text = it, outgoing = true, sent = false) }

    override fun onStartInputView(info: EditorInfo?, restarting: Boolean) {
        super.onStartInputView(info, restarting)
        keyboardState = KeyboardState.IDLE
        replySuggestions = emptyList()
        sentMessages = emptyList()
        errorMessage = null
    }

    override fun onFinishInputView(finishingInput: Boolean) {
        super.onFinishInputView(finishingInput)
        // Don't pause here as the view might be reused
    }

    override fun onDestroy() {
        super.onDestroy()
        lifecycleOwner.onDestroy()
        stopScreenshotService()
    }

    private fun onGenerateClicked() {
        serviceScope.launch {
            val prefs = preferencesRepository.userPreferencesFlow.first()

            // Check if we have auto-generated replies first
            if (autoGeneratedReplies.isNotEmpty()) {
                replySuggestions = autoGeneratedReplies
                keyboardState = KeyboardState.SHOWING_SUGGESTIONS
                return@launch
            }

            // Check if we have a recent screenshot
            val screenshot = latestScreenshot
            val timeSinceScreenshot = System.currentTimeMillis() - screenshotTimestamp

            if (screenshot != null && timeSinceScreenshot < 10000) {
                // Screenshot is recent (less than 10 seconds old), use it!
                generateReplies(screenshot, prefs)
            } else {
                // No recent screenshot, ask user to take one
                keyboardState = KeyboardState.ERROR
                errorMessage = "Take a screenshot (Power + Volume Down), then tap Generate rizz."
            }
        }
    }

    private fun startScreenshotDetectionService() {
        val intent = Intent(this, ScreenshotDetectionService::class.java).apply {
            action = ScreenshotDetectionService.ACTION_START
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            startForegroundService(intent)
        } else {
            startService(intent)
        }
    }

    private fun generateReplies(screenshot: Bitmap, prefs: UserPreferences) {
        serviceScope.launch {
            keyboardState = KeyboardState.GENERATING

            val result = apiService?.generateReplies(screenshot, prefs)

            result?.onSuccess { suggestions ->
                replySuggestions = suggestions
                keyboardState = KeyboardState.SHOWING_SUGGESTIONS
                Log.d("CupidlyKeyboard", "Generated ${suggestions.size} suggestions")
            }?.onFailure { error ->
                keyboardState = KeyboardState.ERROR
                errorMessage = "Failed to generate replies: ${error.message}"
                Log.e("CupidlyKeyboard", "Error generating replies", error)
            }
        }
    }

    private fun onSuggestionClicked(suggestion: String) {
        val ic = currentInputConnection ?: return
        ic.commitText(suggestion, 1)

        // Keep the panel open: move the tapped reply into the sent transcript and
        // drop it from the pending suggestions so follow-ups can continue.
        sentMessages = sentMessages + suggestion
        replySuggestions = replySuggestions.filterNot { it == suggestion }
        autoGeneratedReplies = autoGeneratedReplies.filterNot { it == suggestion }
    }

    private fun openSettings() {
        val intent = Intent(this, MainActivity::class.java).apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        startActivity(intent)
    }

    private fun switchToNextKeyboard() {
        try {
            val imeManager =
                getSystemService(Context.INPUT_METHOD_SERVICE) as android.view.inputmethod.InputMethodManager
            imeManager.showInputMethodPicker()
        } catch (e: Exception) {
            Log.e("CupidlyKeyboard", "Error switching keyboard", e)
        }
    }

    private fun onBackspaceClicked() {
        currentInputConnection?.deleteSurroundingText(1, 0)
    }

    private fun stopScreenshotService() {
        val intent = Intent(this, ScreenshotDetectionService::class.java).apply {
            action = ScreenshotDetectionService.ACTION_STOP
        }
        startService(intent)
        ScreenshotDetectionService.onScreenshotDetected = null
    }
}
