package com.tomfricks.cupidly.keyboard

import android.content.Intent
import android.graphics.Bitmap
import android.inputmethodservice.InputMethodService
import android.os.Build
import android.util.Log
import android.view.View
import android.view.inputmethod.EditorInfo
import androidx.compose.foundation.Image
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.ComposeView
import androidx.compose.ui.platform.ViewCompositionStrategy
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleOwner
import androidx.lifecycle.setViewTreeLifecycleOwner
import androidx.savedstate.setViewTreeSavedStateRegistryOwner
import com.tomfricks.cupidly.MainActivity
import com.tomfricks.cupidly.api.ApiService
import com.tomfricks.cupidly.data.PreferencesRepository
import com.tomfricks.cupidly.data.ThemeMode
import com.tomfricks.cupidly.data.UserPreferences
import com.tomfricks.cupidly.service.ScreenshotDetectionService
import com.tomfricks.cupidly.ui.keyboard.KeyboardMessage
import com.tomfricks.cupidly.ui.keyboard.KeyboardPanel
import com.tomfricks.cupidly.ui.theme.CupidlyTheme
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch

class CupidlyKeyboardService : InputMethodService(), LifecycleOwner {

    private lateinit var preferencesRepository: PreferencesRepository
    private var apiService: ApiService? = null
    private val serviceScope = CoroutineScope(Dispatchers.Main + SupervisorJob())

    private var keyboardState by mutableStateOf(KeyboardState.IDLE)
    private var replySuggestions by mutableStateOf<List<String>>(emptyList())
    private var sentMessages by mutableStateOf<List<String>>(emptyList())
    private var errorMessage by mutableStateOf<String?>(null)
    private var latestScreenshot by mutableStateOf<Bitmap?>(null)

    private var screenshotTimestamp: Long = 0
    private var suggestionsTimestamp: Long = 0
    private var autoGeneratedReplies: List<String> = emptyList()

    override val lifecycle: Lifecycle
        get() = lifecycleOwner.lifecycle

    private val lifecycleOwner = KeyboardLifecycleOwner()

    companion object {
        /** How long freshly generated replies stay on screen between sessions. */
        private const val SUGGESTION_TTL_MS = 5 * 60 * 1000L
    }

    enum class KeyboardState {
        IDLE,
        CAPTURING,
        GENERATING,
        COOKING,
        SHOWING_SUGGESTIONS,
        ERROR
    }

    override fun onCreate() {
        super.onCreate()
        preferencesRepository = PreferencesRepository(this)

        // Initialize API service
        apiService = ApiService()

        // Start screenshot detection service
        startScreenshotDetectionService()

        // A new screenshot is a follow-up in the SAME hidden session: keep the
        // transcript of already-sent messages and the hidden context intact, and
        // only discard the un-picked suggestions before generating fresh ones.
        ScreenshotDetectionService.onScreenshotDetected = { bitmap ->
            latestScreenshot = bitmap
            screenshotTimestamp = System.currentTimeMillis()
            replySuggestions = emptyList()
            autoGeneratedReplies = emptyList()
            errorMessage = null
            keyboardState = KeyboardState.GENERATING
            Log.d("CupidlyKeyboard", "Screenshot detected! Generating replies...")
        }

        // Set up auto-reply generation callback
        ScreenshotDetectionService.onAutoReplyGenerated = { replies ->
            autoGeneratedReplies = replies
            replySuggestions = replies
            suggestionsTimestamp = System.currentTimeMillis()
            keyboardState = KeyboardState.SHOWING_SUGGESTIONS
            Log.d("CupidlyKeyboard", "Auto-generated ${replies.size} replies")
        }

        // Without this the keyboard sits on "Cooking rizz…" forever when the
        // server is unreachable.
        ScreenshotDetectionService.onAutoReplyFailed = { reason ->
            keyboardState = KeyboardState.ERROR
            errorMessage = reason
            Log.d("CupidlyKeyboard", "Auto-reply failed: $reason")
        }

        lifecycleOwner.onCreate()
    }

    override fun onCreateInputView(): View {
        lifecycleOwner.onResume()

        // Set lifecycle owner on the InputMethodService window's DecorView
        window?.window?.decorView?.let { decorView ->
            decorView.setViewTreeLifecycleOwner(lifecycleOwner)
            decorView.setViewTreeSavedStateRegistryOwner(lifecycleOwner)
        }

        return ComposeView(this).apply {
            // Use DisposeOnDetachedFromWindowOrReleasedFromPool strategy for IME
            setViewCompositionStrategy(
                ViewCompositionStrategy.DisposeOnDetachedFromWindowOrReleasedFromPool
            )

            setContent {
                val userPreferences by preferencesRepository.userPreferencesFlow.collectAsState(
                    initial = UserPreferences()
                )

                val systemInDarkTheme = isSystemInDarkTheme()
                val isDarkTheme = when (userPreferences.themeMode) {
                    ThemeMode.LIGHT -> false
                    ThemeMode.DARK -> true
                    ThemeMode.SYSTEM -> systemInDarkTheme
                }

                CupidlyTheme(themeMode = userPreferences.themeMode) {
                    val screenshot = latestScreenshot

                    KeyboardPanel(
                        state = keyboardState,
                        messages = buildTranscript(),
                        errorMessage = errorMessage,
                        isDarkTheme = isDarkTheme,
                        onGenerate = ::onGenerateClicked,
                        onSuggestionClick = ::onSuggestionClicked,
                        onPlusClick = ::openSettings,
                        onNewChatClick = ::onNewChatClicked,
                        onBackspaceClick = ::onBackspaceClicked,
                        thumbnail = if (screenshot != null) {
                            {
                                Image(
                                    bitmap = screenshot.asImageBitmap(),
                                    contentDescription = "Captured screenshot",
                                    contentScale = ContentScale.Crop,
                                    modifier = Modifier.fillMaxSize()
                                )
                            }
                        } else {
                            null
                        }
                    )
                }
            }
        }
    }

    /**
     * Sent replies stay in the transcript above the fresh suggestions, so the
     * conversation reads as a chat you can keep following up in.
     */
    private fun buildTranscript(): List<KeyboardMessage> =
        sentMessages.map { KeyboardMessage(text = it, outgoing = true, sent = true) } +
            replySuggestions.map { KeyboardMessage(text = it, outgoing = true, sent = false) }

    override fun onStartInputView(info: EditorInfo?, restarting: Boolean) {
        super.onStartInputView(info, restarting)

        // Work generated while the keyboard was hidden — the usual case, since
        // you screenshot the chat before opening the keyboard — must survive.
        val hasFreshWork = keyboardState == KeyboardState.GENERATING ||
            keyboardState == KeyboardState.COOKING ||
            (replySuggestions.isNotEmpty() &&
                System.currentTimeMillis() - suggestionsTimestamp < SUGGESTION_TTL_MS)

        if (!hasFreshWork) {
            keyboardState = KeyboardState.IDLE
            replySuggestions = emptyList()
            sentMessages = emptyList()
            autoGeneratedReplies = emptyList()
            errorMessage = null
        }
    }

    override fun onFinishInputView(finishingInput: Boolean) {
        super.onFinishInputView(finishingInput)
        // Don't pause here as the view might be reused
    }

    override fun onDestroy() {
        super.onDestroy()
        lifecycleOwner.onDestroy()
        stopScreenshotService()
    }

    private fun onGenerateClicked() {
        serviceScope.launch {
            val prefs = preferencesRepository.userPreferencesFlow.first()

            // Check if we have auto-generated replies first
            if (autoGeneratedReplies.isNotEmpty()) {
                replySuggestions = autoGeneratedReplies
                keyboardState = KeyboardState.SHOWING_SUGGESTIONS
                return@launch
            }

            // Check if we have a recent screenshot
            val screenshot = latestScreenshot
            val timeSinceScreenshot = System.currentTimeMillis() - screenshotTimestamp

            if (screenshot != null && timeSinceScreenshot < 10000) {
                // Screenshot is recent (less than 10 seconds old), use it!
                generateReplies(screenshot, prefs)
            } else {
                // No recent screenshot, ask user to take one
                keyboardState = KeyboardState.ERROR
                errorMessage = "Take a screenshot (Power + Volume Down), then tap Generate rizz."
            }
        }
    }

    private fun startScreenshotDetectionService() {
        val intent = Intent(this, ScreenshotDetectionService::class.java).apply {
            action = ScreenshotDetectionService.ACTION_START
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            startForegroundService(intent)
        } else {
            startService(intent)
        }
    }

    private fun generateReplies(screenshot: Bitmap, prefs: UserPreferences) {
        serviceScope.launch {
            keyboardState = KeyboardState.GENERATING

            val currentContext = ConversationSession.conversationContext
            val result = apiService?.generateReplies(screenshot, prefs, currentContext)

            result?.onSuccess { generated ->
                ConversationSession.update(generated.context)
                replySuggestions = generated.suggestions
                suggestionsTimestamp = System.currentTimeMillis()
                keyboardState = KeyboardState.SHOWING_SUGGESTIONS
                Log.d("CupidlyKeyboard", "Generated ${generated.suggestions.size} suggestions")
            }?.onFailure { error ->
                keyboardState = KeyboardState.ERROR
                errorMessage = "Failed to generate replies: ${error.message}"
                Log.e("CupidlyKeyboard", "Error generating replies", error)
            }
        }
    }

    private fun onSuggestionClicked(suggestion: String) {
        val ic = currentInputConnection ?: return
        ic.commitText(suggestion, 1)

        // Keep the chosen reply and delete the rest: move it into the sent
        // transcript, clear every other pending suggestion, and record it in the
        // hidden session context so the next generation knows what was sent.
        sentMessages = sentMessages + suggestion
        replySuggestions = emptyList()
        autoGeneratedReplies = emptyList()
        ConversationSession.recordSentReply(suggestion)
    }

    private fun openSettings() {
        val intent = Intent(this, MainActivity::class.java).apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        startActivity(intent)
    }

    /**
     * Start a fresh session: wipe the hidden conversation context and every
     * on-screen trace so the next screenshot begins a brand-new conversation.
     */
    private fun onNewChatClicked() {
        ConversationSession.reset()
        replySuggestions = emptyList()
        sentMessages = emptyList()
        autoGeneratedReplies = emptyList()
        latestScreenshot = null
        errorMessage = null
        screenshotTimestamp = 0
        suggestionsTimestamp = 0
        keyboardState = KeyboardState.IDLE
        Log.d("CupidlyKeyboard", "New session started")
    }

    private fun onBackspaceClicked() {
        currentInputConnection?.deleteSurroundingText(1, 0)
    }

    private fun stopScreenshotService() {
        val intent = Intent(this, ScreenshotDetectionService::class.java).apply {
            action = ScreenshotDetectionService.ACTION_STOP
        }
        startService(intent)
        ScreenshotDetectionService.onScreenshotDetected = null
        ScreenshotDetectionService.onAutoReplyGenerated = null
        ScreenshotDetectionService.onAutoReplyFailed = null
    }
}
